### PR TITLE
BusinessInsider: multiple Updates

### PR DESCRIPTION
**Pull request by addie9800**
I have updated the title parser due to the former version using the <title> tags value which doesn't coincide with the actual headline of the article. 
I have also addressed the issue of external contents being parsed with errors

### CODE REVIEW

**Comment by MaxDall** [comment]
Hey @addie9800 thanks for fixing this 👍 Could you explain to me why this PR also adds a new test case for the publisher?

**Comment by addie9800** [comment]
> Hey @addie9800 thanks for fixing this 👍 Could you explain to me why this PR also adds a new test case for the publisher?

I just realized the mistake in my train of thought: My thought was that with the updated selector, we would also need to update the testcase, because I was thinking of the version in the PR with the body added to the unit tests.

**Comment by MaxDall** [comment]
@addie9800 Could you open your changes in a new PR that does not alter the test case?

**Comment by MaxDall** [comment]
@addie9800 Thanks a lot. I will close this now.

**Pull request closed without merging**
