### PR TITLE
Norwegian publishers

### PR DESCRIPTION
**Pull request by mhaugestad**
Added 4 Norwegian publishers: 
VG, Dagbladet, Nettavisen and NRK

Ran `black src`, `isort src` as per the guide which did change some files that were not mine.

### CODE REVIEW

**Review by MaxDall — COMMENTED** [review]
Thanks a lot for the huge effort! That looks really nice and will be a huge addition to Fundus. I add some review comments here to explain my changes but will commit my work onto this branch.

**Comment by MaxDall** [comment]
@mhaugestad I will merge this into the master branch and make a new release 🚀

**Comment by mhaugestad** [comment]
Amazing! Thank you @MaxDall . Will keep comments and changes in mind for my next pull request. Hoping to add some more Scandinavian publishers over the next month!

**Comment by MaxDall** [comment]
@mhaugestad Sounds Awesome!

**Pull request merged**
